import Foundation

struct WorldCity: Identifiable {
    let id = UUID()
    let city: String
    let country: String
    let timeZoneId: String
    
    var searchKey: String {
        "\(city) \(country)".lowercased()
    }
}

class WorldClockData {
    static let allCities: [WorldCity] = [
        // Africa
        WorldCity(city: "Abidjan", country: "Côte d'Ivoire", timeZoneId: "Africa/Abidjan"),
        WorldCity(city: "Accra", country: "Ghana", timeZoneId: "Africa/Accra"),
        WorldCity(city: "Addis Ababa", country: "Ethiopia", timeZoneId: "Africa/Addis_Ababa"),
        WorldCity(city: "Algiers", country: "Algeria", timeZoneId: "Africa/Algiers"),
        WorldCity(city: "Cairo", country: "Egypt", timeZoneId: "Africa/Cairo"),
        WorldCity(city: "Casablanca", country: "Morocco", timeZoneId: "Africa/Casablanca"),
        WorldCity(city: "Johannesburg", country: "South Africa", timeZoneId: "Africa/Johannesburg"),
        WorldCity(city: "Lagos", country: "Nigeria", timeZoneId: "Africa/Lagos"),
        WorldCity(city: "Nairobi", country: "Kenya", timeZoneId: "Africa/Nairobi"),
        WorldCity(city: "Tunis", country: "Tunisia", timeZoneId: "Africa/Tunis"),
        
        // Americas
        WorldCity(city: "Anchorage", country: "USA", timeZoneId: "America/Anchorage"),
        WorldCity(city: "Asunción", country: "Paraguay", timeZoneId: "America/Asuncion"),
        WorldCity(city: "Atlanta", country: "USA", timeZoneId: "America/New_York"),
        WorldCity(city: "Austin", country: "USA", timeZoneId: "America/Chicago"),
        WorldCity(city: "Bogotá", country: "Colombia", timeZoneId: "America/Bogota"),
        WorldCity(city: "Boston", country: "USA", timeZoneId: "America/New_York"),
        WorldCity(city: "Brasília", country: "Brazil", timeZoneId: "America/Sao_Paulo"),
        WorldCity(city: "Buenos Aires", country: "Argentina", timeZoneId: "America/Argentina/Buenos_Aires"),
        WorldCity(city: "Caracas", country: "Venezuela", timeZoneId: "America/Caracas"),
        WorldCity(city: "Chicago", country: "USA", timeZoneId: "America/Chicago"),
        WorldCity(city: "Cupertino", country: "USA", timeZoneId: "America/Los_Angeles"),
        WorldCity(city: "Dallas", country: "USA", timeZoneId: "America/Chicago"),
        WorldCity(city: "Denver", country: "USA", timeZoneId: "America/Denver"),
        WorldCity(city: "Detroit", country: "USA", timeZoneId: "America/Detroit"),
        WorldCity(city: "Guatemala City", country: "Guatemala", timeZoneId: "America/Guatemala"),
        WorldCity(city: "Havana", country: "Cuba", timeZoneId: "America/Havana"),
        WorldCity(city: "Honolulu", country: "USA", timeZoneId: "Pacific/Honolulu"),
        WorldCity(city: "Houston", country: "USA", timeZoneId: "America/Chicago"),
        WorldCity(city: "Lima", country: "Peru", timeZoneId: "America/Lima"),
        WorldCity(city: "Los Angeles", country: "USA", timeZoneId: "America/Los_Angeles"),
        WorldCity(city: "Mexico City", country: "Mexico", timeZoneId: "America/Mexico_City"),
        WorldCity(city: "Miami", country: "USA", timeZoneId: "America/New_York"),
        WorldCity(city: "Minneapolis", country: "USA", timeZoneId: "America/Chicago"),
        WorldCity(city: "Montevideo", country: "Uruguay", timeZoneId: "America/Montevideo"),
        WorldCity(city: "Montreal", country: "Canada", timeZoneId: "America/Montreal"),
        WorldCity(city: "New York", country: "USA", timeZoneId: "America/New_York"),
        WorldCity(city: "Panama City", country: "Panama", timeZoneId: "America/Panama"),
        WorldCity(city: "Phoenix", country: "USA", timeZoneId: "America/Phoenix"),
        WorldCity(city: "Philadelphia", country: "USA", timeZoneId: "America/New_York"),
        WorldCity(city: "Rio de Janeiro", country: "Brazil", timeZoneId: "America/Sao_Paulo"),
        WorldCity(city: "San Francisco", country: "USA", timeZoneId: "America/Los_Angeles"),
        WorldCity(city: "Santiago", country: "Chile", timeZoneId: "America/Santiago"),
        WorldCity(city: "São Paulo", country: "Brazil", timeZoneId: "America/Sao_Paulo"),
        WorldCity(city: "Seattle", country: "USA", timeZoneId: "America/Los_Angeles"),
        WorldCity(city: "Toronto", country: "Canada", timeZoneId: "America/Toronto"),
        WorldCity(city: "Vancouver", country: "Canada", timeZoneId: "America/Vancouver"),
        WorldCity(city: "Washington D.C.", country: "USA", timeZoneId: "America/New_York"),
        
        // Asia
        WorldCity(city: "Almaty", country: "Kazakhstan", timeZoneId: "Asia/Almaty"),
        WorldCity(city: "Amman", country: "Jordan", timeZoneId: "Asia/Amman"),
        WorldCity(city: "Baghdad", country: "Iraq", timeZoneId: "Asia/Baghdad"),
        WorldCity(city: "Bangalore", country: "India", timeZoneId: "Asia/Kolkata"),
        WorldCity(city: "Bangkok", country: "Thailand", timeZoneId: "Asia/Bangkok"),
        WorldCity(city: "Beijing", country: "China", timeZoneId: "Asia/Shanghai"),
        WorldCity(city: "Beirut", country: "Lebanon", timeZoneId: "Asia/Beirut"),
        WorldCity(city: "Chennai", country: "India", timeZoneId: "Asia/Kolkata"),
        WorldCity(city: "Damascus", country: "Syria", timeZoneId: "Asia/Damascus"),
        WorldCity(city: "Dhaka", country: "Bangladesh", timeZoneId: "Asia/Dhaka"),
        WorldCity(city: "Dubai", country: "UAE", timeZoneId: "Asia/Dubai"),
        WorldCity(city: "Hanoi", country: "Vietnam", timeZoneId: "Asia/Bangkok"),
        WorldCity(city: "Ho Chi Minh City", country: "Vietnam", timeZoneId: "Asia/Bangkok"),
        WorldCity(city: "Hong Kong", country: "China", timeZoneId: "Asia/Hong_Kong"),
        WorldCity(city: "Jakarta", country: "Indonesia", timeZoneId: "Asia/Jakarta"),
        WorldCity(city: "Jerusalem", country: "Israel", timeZoneId: "Asia/Jerusalem"),
        WorldCity(city: "Kabul", country: "Afghanistan", timeZoneId: "Asia/Kabul"),
        WorldCity(city: "Karachi", country: "Pakistan", timeZoneId: "Asia/Karachi"),
        WorldCity(city: "Kathmandu", country: "Nepal", timeZoneId: "Asia/Kathmandu"),
        WorldCity(city: "Kolkata", country: "India", timeZoneId: "Asia/Kolkata"),
        WorldCity(city: "Kuala Lumpur", country: "Malaysia", timeZoneId: "Asia/Kuala_Lumpur"),
        WorldCity(city: "Kuwait City", country: "Kuwait", timeZoneId: "Asia/Kuwait"),
        WorldCity(city: "Manila", country: "Philippines", timeZoneId: "Asia/Manila"),
        WorldCity(city: "Mumbai", country: "India", timeZoneId: "Asia/Kolkata"),
        WorldCity(city: "New Delhi", country: "India", timeZoneId: "Asia/Kolkata"),
        WorldCity(city: "Osaka", country: "Japan", timeZoneId: "Asia/Tokyo"),
        WorldCity(city: "Phnom Penh", country: "Cambodia", timeZoneId: "Asia/Phnom_Penh"),
        WorldCity(city: "Pyongyang", country: "North Korea", timeZoneId: "Asia/Pyongyang"),
        WorldCity(city: "Riyadh", country: "Saudi Arabia", timeZoneId: "Asia/Riyadh"),
        WorldCity(city: "Seoul", country: "South Korea", timeZoneId: "Asia/Seoul"),
        WorldCity(city: "Shanghai", country: "China", timeZoneId: "Asia/Shanghai"),
        WorldCity(city: "Singapore", country: "Singapore", timeZoneId: "Asia/Singapore"),
        WorldCity(city: "Taipei", country: "Taiwan", timeZoneId: "Asia/Taipei"),
        WorldCity(city: "Tashkent", country: "Uzbekistan", timeZoneId: "Asia/Tashkent"),
        WorldCity(city: "Tehran", country: "Iran", timeZoneId: "Asia/Tehran"),
        WorldCity(city: "Tel Aviv", country: "Israel", timeZoneId: "Asia/Tel_Aviv"),
        WorldCity(city: "Tokyo", country: "Japan", timeZoneId: "Asia/Tokyo"),
        WorldCity(city: "Yangon", country: "Myanmar", timeZoneId: "Asia/Yangon"),

        // Europe
        WorldCity(city: "Amsterdam", country: "Netherlands", timeZoneId: "Europe/Amsterdam"),
        WorldCity(city: "Athens", country: "Greece", timeZoneId: "Europe/Athens"),
        WorldCity(city: "Barcelona", country: "Spain", timeZoneId: "Europe/Madrid"),
        WorldCity(city: "Belgrade", country: "Serbia", timeZoneId: "Europe/Belgrade"),
        WorldCity(city: "Berlin", country: "Germany", timeZoneId: "Europe/Berlin"),
        WorldCity(city: "Brussels", country: "Belgium", timeZoneId: "Europe/Brussels"),
        WorldCity(city: "Bucharest", country: "Romania", timeZoneId: "Europe/Bucharest"),
        WorldCity(city: "Budapest", country: "Hungary", timeZoneId: "Europe/Budapest"),
        WorldCity(city: "Copenhagen", country: "Denmark", timeZoneId: "Europe/Copenhagen"),
        WorldCity(city: "Dublin", country: "Ireland", timeZoneId: "Europe/Dublin"),
        WorldCity(city: "Geneva", country: "Switzerland", timeZoneId: "Europe/Zurich"),
        WorldCity(city: "Helsinki", country: "Finland", timeZoneId: "Europe/Helsinki"),
        WorldCity(city: "Istanbul", country: "Turkey", timeZoneId: "Europe/Istanbul"),
        WorldCity(city: "Kyiv", country: "Ukraine", timeZoneId: "Europe/Kiev"),
        WorldCity(city: "Lisbon", country: "Portugal", timeZoneId: "Europe/Lisbon"),
        WorldCity(city: "London", country: "UK", timeZoneId: "Europe/London"),
        WorldCity(city: "Madrid", country: "Spain", timeZoneId: "Europe/Madrid"),
        WorldCity(city: "Milan", country: "Italy", timeZoneId: "Europe/Rome"),
        WorldCity(city: "Moscow", country: "Russia", timeZoneId: "Europe/Moscow"),
        WorldCity(city: "Munich", country: "Germany", timeZoneId: "Europe/Berlin"),
        WorldCity(city: "Oslo", country: "Norway", timeZoneId: "Europe/Oslo"),
        WorldCity(city: "Paris", country: "France", timeZoneId: "Europe/Paris"),
        WorldCity(city: "Prague", country: "Czech Republic", timeZoneId: "Europe/Prague"),
        WorldCity(city: "Rome", country: "Italy", timeZoneId: "Europe/Rome"),
        WorldCity(city: "Stockholm", country: "Sweden", timeZoneId: "Europe/Stockholm"),
        WorldCity(city: "Vienna", country: "Austria", timeZoneId: "Europe/Vienna"),
        WorldCity(city: "Warsaw", country: "Poland", timeZoneId: "Europe/Warsaw"),
        WorldCity(city: "Zurich", country: "Switzerland", timeZoneId: "Europe/Zurich"),

        // Oceania / Pacific
        WorldCity(city: "Auckland", country: "New Zealand", timeZoneId: "Pacific/Auckland"),
        WorldCity(city: "Brisbane", country: "Australia", timeZoneId: "Australia/Brisbane"),
        WorldCity(city: "Melbourne", country: "Australia", timeZoneId: "Australia/Melbourne"),
        WorldCity(city: "Perth", country: "Australia", timeZoneId: "Australia/Perth"),
        WorldCity(city: "Suva", country: "Fiji", timeZoneId: "Pacific/Fiji"),
        WorldCity(city: "Sydney", country: "Australia", timeZoneId: "Australia/Sydney")
    ]
}
